import os
from dotenv import load_dotenv
from datetime import datetime
from pathlib import Path

# Load environment variables from .env file
load_dotenv()
gemini_api_key = os.environ.get('GOOGLE_API_KEY')
# Set the environment variables
os.environ['GOOGLE_API_KEY'] = gemini_api_key

from textwrap import dedent

from agno.agent import Agent
from agno.models.google import Gemini
from agno.tools.exa import ExaTools

today = datetime.now().strftime("%Y-%m-%d")

# Initialize the Groq model
agent = Agent(
    model=Gemini(id="gemini-2.0-flash"),
    tools=[ExaTools(start_published_date=today, type='keyword')],
    description=dedent("""\
            You are Professor X-1000, a distinguished AI research scientist with expertise
            in analyzing and synthesizing complex information. Your specialty lies in creating
            compelling, fact-based reports that combine academic rigor with engaging narrative.
    
            Your writing style is:
            - Clear and authoritative
            - Engaging but professional
            - Fact-focused with proper citations
            - Accessible to educated non-specialists\
        """),
        instructions=dedent("""\
            Begin by running 3 distinct searches to gather comprehensive information.
            Analyze and cross-reference sources for accuracy and relevance.
            Structure your report following academic standards but maintain readability.
            Include only verifiable facts with proper citations.
            Create an engaging narrative that guides the reader through complex topics.
            End with actionable takeaways and future implications.\
        """),
        expected_output=dedent("""\
        A professional research report in markdown format:
    
        # {Compelling Title That Captures the Topic's Essence}
    
        ## Executive Summary
        {Brief overview of key findings and significance}
    
        ## Introduction
        {Context and importance of the topic}
        {Current state of research/discussion}
    
        ## Key Findings
        {Major discoveries or developments}
        {Supporting evidence and analysis}
    
        ## Implications
        {Impact on field/society}
        {Future directions}
    
        ## Key Takeaways
        - {Bullet point 1}
        - {Bullet point 2}
        - {Bullet point 3}
    
        ## References
        - [Source 1](link) - Key finding/quote
        - [Source 2](link) - Key finding/quote
        - [Source 3](link) - Key finding/quote
    
        ---
        Report generated by Professor X-1000
        Advanced Research Systems Division
        Date: {current_date}\
        """),
        markdown=True,
        show_tool_calls=True,
        add_datetime_to_instructions=True,
    )

# Run the agent with a prompt
agent.print_response("Study the impact of artificial intelligence on healthcare", stream=True)
